context:
  version: "0.2.0"

package:
  name: jupyter-server-mcp
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-server-mcp/jupyter_server_mcp-${{ version }}.tar.gz
  sha256: 9f4fcfcf7eab32a07c7f9381e285ea06237128275a72b0a3e6289dde6c58312d

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.5
  run:
    - python >=${{ python_min }}
    - fastmcp >=3.2.4
    - jupyter_server >=1.6,<3

tests:
  - python:
      imports:
        - jupyter_server_mcp
      pip_check: true
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/jupyter-ai-contrib/jupyter-server-mcp
  summary: "An MCP interface/extension for Jupyter Server"
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://jupyter-ai.readthedocs.io/
  repository: https://github.com/jupyter-ai-contrib/jupyter-server-mcp

extra:
  recipe-maintainers:
    - dlqqq
    - andrii-i
