context:
  version: "0.2.1"

package:
  name: jupyter-server-mcp
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-server-mcp/jupyter_server_mcp-${{ version }}.tar.gz
  sha256: 41392496ced1d8de441fbcfff7c31b3fc2767abaa350e25660bbcc8aa5c8a9ae

build:
  noarch: python
  script: python -m pip install . -vv
  number: 1

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.5
  run:
    - python >=${{ python_min }}
    - fastmcp >=2.0.0
    # TODO: remove once https://github.com/conda-forge/authlib-feedstock/pull/46 is merged
    - joserfc >=1.6
    - jupyter_server >=1.6,<3

tests:
  - python:
      imports:
        - jupyter_server_mcp
      pip_check: true
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/jupyter-ai-contrib/jupyter-server-mcp
  summary: "An MCP interface/extension for Jupyter Server"
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://jupyter-ai.readthedocs.io/
  repository: https://github.com/jupyter-ai-contrib/jupyter-server-mcp

extra:
  recipe-maintainers:
    - dlqqq
    - andrii-i
